# SOPS configuration - uses age encryption
# Local key: SSH key converted to age (just age-setup)
# Server key: sops-nix generates at /var/lib/sops-nix/key.txt (just host-key)

keys:
  # goksel's age key (from SSH key via ssh-to-age)
  - &goksel age1kz7n7l8rgu3cpwf5wyyleslanjnavglgmstvlfqmshw424mvpfssy4sy3y

  # hl-node01's age key (derived from SSH host key via ssh-to-age)
  # Get with: just host-key hl-node01
  # After reinstall: update this key and run `just secrets-update`
  - &hl-node01 age1qene8xdfrnyxc68s60rt6rqtq4rxnd6fnhwxxg3fns7gt46ypqsqfdapa0

creation_rules:
  # NixOS system secrets (encrypt to both user + host)
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *goksel
          - *hl-node01

  # Home-manager user secrets (user key only)
  - path_regex: home/secrets/.*\.yaml$
    key_groups:
      - age:
          - *goksel

  # Kubernetes secrets (encrypt to both for ksops on server)
  - path_regex: manifests/.*secret.*\.yaml$
    key_groups:
      - age:
          - *goksel
          - *hl-node01
