# SOPS configuration - uses age encryption
# User key: SSH key converted to age (just age-setup)
# Host key: SSH host key converted to age (just host-key <hostname>)

keys:
  # goksel's age key (from SSH key via ssh-to-age)
  - &goksel age1kz7n7l8rgu3cpwf5wyyleslanjnavglgmstvlfqmshw424mvpfssy4sy3y

  # hl-node01's age key (from SSH host key via ssh-to-age)
  # Get with: just host-key hl-node01
  # After reinstall: update this key and run `just secrets-rekey`
  - &hl-node01 age1mwa0pc8hu6cnz36duaq6rt7afu0xfvzm7h5lvznrxdk0q8zdm3sszcw9zf

creation_rules:
  # Host secrets (encrypt to user + hosts)
  - path_regex: secrets/hosts/.*\.yaml$
    key_groups:
      - age:
          - *goksel
          - *hl-node01

  # User secrets (encrypt to user only)
  - path_regex: secrets/users/.*\.yaml$
    key_groups:
      - age:
          - *goksel
